#!/bin/sh
# https://github.com/angular/components/wiki/Pre-commit-hook-for-linters
PATH=$PATH:/usr/local/bin:/usr/local/sbin

pass=true
RED='\033[1;31m'
GREEN='\033[0;32m'
NC='\033[0m'

#
# Prevent commit on master
#
currentBranch=$(git branch | sed -n -e 's/^\* \(.*\)/\1/p')

if [ "$currentBranch" == "master" ]; then
  echo "${RED}\nDo not commit to master!${NC}\n"
  exit 1
fi

#
# Lint the code
#
echo "pre-push hook: lint"

# Run lint and get the output and return code
lint=$(npm run lint)
ret_code=$?

# If it didn't pass, announce it failed and print the output
if [ $ret_code != 0 ]; then
	printf "\n${RED}lint failed:${NC}"
	echo "$lint\n"
	pass=false
else
	printf "${GREEN}lint passed.${NC}\n"
  echo "$lint\n"
fi

# If there were no failures, it is good to commit
if $pass; then
	exit 0
fi

exit 1
